// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Weather.Infrastructure.Data.Contexts;

#nullable disable

namespace Weather.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20260213032620_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Weather.Core.Domain.DeviceData", b =>
                {
                    b.Property<long>("DateUtc")
                        .HasColumnType("bigint")
                        .HasJsonPropertyName("dateutc");

                    b.Property<double>("BaromAbs")
                        .HasColumnType("float")
                        .HasJsonPropertyName("baromabsin");

                    b.Property<double>("BaromRel")
                        .HasColumnType("float")
                        .HasJsonPropertyName("baromrelin");

                    b.Property<bool>("BattCo2")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("batt_co2");

                    b.Property<bool>("BattOut")
                        .HasColumnType("bit")
                        .HasJsonPropertyName("battout");

                    b.Property<double>("DailyRain")
                        .HasColumnType("float")
                        .HasJsonPropertyName("dailyrainin");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasJsonPropertyName("date");

                    b.Property<double>("DewPoint")
                        .HasColumnType("float")
                        .HasJsonPropertyName("dewPoint");

                    b.Property<double>("DewPointIn")
                        .HasColumnType("float")
                        .HasJsonPropertyName("dewPointin");

                    b.Property<double>("EventRain")
                        .HasColumnType("float")
                        .HasJsonPropertyName("eventrainin");

                    b.Property<double>("FeelsLike")
                        .HasColumnType("float")
                        .HasJsonPropertyName("feelsLike");

                    b.Property<double>("FeelsLikeIn")
                        .HasColumnType("float")
                        .HasJsonPropertyName("feelsLikein");

                    b.Property<double>("HourlyRainRate")
                        .HasColumnType("float")
                        .HasJsonPropertyName("hourlyrainin");

                    b.Property<int>("HumidityIn")
                        .HasColumnType("int")
                        .HasJsonPropertyName("humidityin");

                    b.Property<int>("HumidityOut")
                        .HasColumnType("int")
                        .HasJsonPropertyName("humidity");

                    b.Property<string>("Loc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasJsonPropertyName("loc");

                    b.Property<double>("MaxDailyGust")
                        .HasColumnType("float")
                        .HasJsonPropertyName("maxdailygust");

                    b.Property<double>("MonthlyRain")
                        .HasColumnType("float")
                        .HasJsonPropertyName("monthlyrainin");

                    b.Property<double>("SolarRadiation")
                        .HasColumnType("float")
                        .HasJsonPropertyName("solarradiation");

                    b.Property<double>("TempIn")
                        .HasColumnType("float")
                        .HasJsonPropertyName("tempinf");

                    b.Property<double>("TempOut")
                        .HasColumnType("float")
                        .HasJsonPropertyName("tempf");

                    b.Property<double>("TotalRain")
                        .HasColumnType("float")
                        .HasJsonPropertyName("totalrainin");

                    b.Property<int>("Uv")
                        .HasColumnType("int")
                        .HasJsonPropertyName("uv");

                    b.Property<double>("WeeklyRain")
                        .HasColumnType("float")
                        .HasJsonPropertyName("weeklyrainin");

                    b.Property<int>("WindDir")
                        .HasColumnType("int")
                        .HasJsonPropertyName("winddir");

                    b.Property<double>("WindGust")
                        .HasColumnType("float")
                        .HasJsonPropertyName("windgustmph");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("float")
                        .HasJsonPropertyName("windspeedmph");

                    b.HasKey("DateUtc");

                    b.ToTable("DeviceData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
