CREATE TABLE [dbo].[DeviceData]
(
    [DateUtc] BIGINT NOT NULL,
	[TempIn] FLOAT NOT NULL,
	[HumidityIn] INT NOT NULL,
	[BaromRel] FLOAT NOT NULL,
	[BaromAbs] FLOAT NOT NULL,
	[TempOut] FLOAT NOT NULL,
	[BattOut] BIT NOT NULL,
	[HumidityOut] INT NOT NULL,
	[WindDir] INT NOT NULL,
	[WindSpeed] FLOAT NOT NULL,
	[WindGust] FLOAT NOT NULL,
	[MaxDailyGust] FLOAT NOT NULL,
	[HourlyRainRate] FLOAT NOT NULL,
	[EventRain] FLOAT NOT NULL,
	[DailyRain] FLOAT NOT NULL,
	[WeeklyRain] FLOAT NOT NULL,
	[MonthlyRain] FLOAT NOT NULL,
	[TotalRain] FLOAT NOT NULL,
	[SolarRadiation] FLOAT NOT NULL,
	[Uv] INT NOT NULL,
	[BattCo2] BIT NOT NULL,
	[FeelsLike] FLOAT NOT NULL,
	[DewPoint] FLOAT NOT NULL,
	[FeelsLikeIn] FLOAT NOT NULL,
	[DewPointIn] FLOAT NOT NULL,
	[Loc] VARCHAR(50) NOT NULL,
	[Date] DATETIME NOT NULL, 
    CONSTRAINT [PK_DeviceData] PRIMARY KEY ([DateUtc]),
)
